name: CI

on:
  pull_request:
  push:
    branches: ['master']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: [self-hosted, common]
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v10
      - name: Cache scala dependencies
        uses: coursier/cache-action@v5
      - name: Lint code
        run: sbt check

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: ['adopt@1.8', 'adopt@1.11']
        scala: ['2.13.8', '3.1.3']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v5
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test
