name: CI

on:
  pull_request:
  push:
    branches: ['series/2.x']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: coursier/setup-action@v2
      - name: Cache scala dependencies
        uses: coursier/cache-action@v8
      - name: Lint code
        run: sbt check

  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: ['adoptium:17']
        scala: ['2.12.21', '2.13.18', '3.3.7']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: coursier/setup-action@v2
        with:
          jvm: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v8
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test
        
  publish:
    runs-on: ubuntu-24.04
    needs: [lint, test]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: coursier/setup-action@v2
        with:
          jvm: adoptium:17
      - name: Cache scala dependencies
        uses: coursier/cache-action@v8
      - name: Release artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
