name: Build and Deploy Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'series/2.x' || github.ref == 'refs/heads/series/2.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: vuepress-deploy
        uses: IT4Change/vuepress-build-and-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd vuepress && yarn install && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist/
